"""core schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 07:53:35.989772
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_state',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('quarantined_records',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=160), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantined_records_received_at'), 'quarantined_records', ['received_at'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('source_name', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('last_successful_fetch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_data_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('records_last_batch', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_geospatial_table('zones',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('boundary_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_zones_geometry', 'zones', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('anomalies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('baseline_low', sa.Float(), nullable=False),
    sa.Column('baseline_high', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('detector_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'timestamp', 'parameter', 'detector_version', name='uq_anomaly')
    )
    op.create_index('ix_anomalies_zone_ts', 'anomalies', ['zone_id', 'timestamp'], unique=False)
    op.create_table('aqi_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('dominant_parameter', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('method', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'timestamp', 'source', name='uq_aqi_zone_ts_source')
    )
    op.create_geospatial_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id')
    )
    op.create_geospatial_index('idx_events_location', 'events', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_events_time_zone', 'events', ['start_time', 'end_time', 'zone_id'], unique=False)
    op.create_geospatial_table('factories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_factories_geometry', 'factories', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_factories_zone_id'), 'factories', ['zone_id'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source_window', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'timestamp', 'feature_name', name='uq_feature')
    )
    op.create_index('ix_features_zone_name_ts', 'features', ['zone_id', 'feature_name', 'timestamp'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('based_on_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('validation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_run_id'), 'forecasts', ['run_id'], unique=False)
    op.create_index('ix_forecasts_zone_param_target', 'forecasts', ['zone_id', 'parameter', 'target_time'], unique=False)
    op.create_geospatial_table('sensors',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('parameters', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_sensors_geometry', 'sensors', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_sensors_zone_id'), 'sensors', ['zone_id'], unique=False)
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=True),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('persistence_windows', sa.Integer(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('peak_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('episode_open', sa.Boolean(), nullable=False),
    sa.Column('breach_windows', sa.Integer(), nullable=False),
    sa.Column('first_breach_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_breach_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=80), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['threshold_id'], ['thresholds.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_zone_status_created', 'alerts', ['zone_id', 'status', 'created_at'], unique=False)
    op.create_index('uq_alerts_open_episode', 'alerts', ['zone_id', 'parameter', 'threshold_id'], unique=True, postgresql_where=sa.text('episode_open'))
    op.create_table('attributions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.Column('contributor_type', sa.String(length=20), nullable=False),
    sa.Column('contributor_id', sa.String(length=80), nullable=False),
    sa.Column('contributor_name', sa.String(length=160), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('best_lag_windows', sa.Integer(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributions_anomaly_id'), 'attributions', ['anomaly_id'], unique=False)
    op.create_table('factory_outputs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('factory_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('operating_state', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'timestamp', 'metric', name='uq_factory_output')
    )
    op.create_index('ix_factory_outputs_ts_factory', 'factory_outputs', ['timestamp', 'factory_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensor_id', sa.String(length=80), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('original_timestamp', sa.String(length=64), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quality_flag', sa.String(length=12), nullable=False),
    sa.Column('quality_reason', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id', 'timestamp'),
    sa.UniqueConstraint('source', 'source_record_id', 'timestamp', name='uq_readings_source_record')
    )
    op.create_index('ix_readings_created_at', 'readings', ['created_at'], unique=False)
    op.create_index('ix_readings_ts_zone_param', 'readings', ['timestamp', 'zone_id', 'parameter'], unique=False)
    op.create_table('water_observations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sensor_id', sa.String(length=80), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'timestamp', 'parameter', name='uq_water_obs')
    )
    op.create_index('ix_water_obs_zone_ts', 'water_observations', ['zone_id', 'timestamp'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('zone_id', sa.String(length=40), nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('anomaly_id', sa.BigInteger(), nullable=True),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('contributor_type', sa.String(length=20), nullable=True),
    sa.Column('contributor_id', sa.String(length=80), nullable=True),
    sa.Column('operator', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_water_obs_zone_ts', table_name='water_observations')
    op.drop_table('water_observations')
    op.drop_index('ix_readings_ts_zone_param', table_name='readings')
    op.drop_index('ix_readings_created_at', table_name='readings')
    op.drop_table('readings')
    op.drop_index('ix_factory_outputs_ts_factory', table_name='factory_outputs')
    op.drop_table('factory_outputs')
    op.drop_index(op.f('ix_attributions_anomaly_id'), table_name='attributions')
    op.drop_table('attributions')
    op.drop_index('uq_alerts_open_episode', table_name='alerts', postgresql_where=sa.text('episode_open'))
    op.drop_index('ix_alerts_zone_status_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('thresholds')
    op.drop_index(op.f('ix_sensors_zone_id'), table_name='sensors')
    op.drop_geospatial_index('idx_sensors_geometry', table_name='sensors', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('sensors')
    op.drop_index('ix_forecasts_zone_param_target', table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_run_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_features_zone_name_ts', table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_factories_zone_id'), table_name='factories')
    op.drop_geospatial_index('idx_factories_geometry', table_name='factories', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('factories')
    op.drop_index('ix_events_time_zone', table_name='events')
    op.drop_geospatial_index('idx_events_location', table_name='events', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('events')
    op.drop_table('aqi_snapshots')
    op.drop_index('ix_anomalies_zone_ts', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_geospatial_index('idx_zones_geometry', table_name='zones', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('zones')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_quarantined_records_received_at'), table_name='quarantined_records')
    op.drop_table('quarantined_records')
    op.drop_table('pipeline_state')
    # ### end Alembic commands ###
